export interface NoiseEvent {
  id: string;
  dayMin: number;
  dayMax: number;
  phase: 'euphoria' | 'sideways' | 'decline' | 'crash' | 'recovery';
  headline: string;
  socialPost: string;
  source: string;
  bias: 'bull' | 'bear' | 'fear' | 'euphoria';
  correctAction: 'ignore' | 'investigate' | 'hedge';
  whyTempting: string;
  lessonIfFollowed: string;
}

export function pickNoiseEvents(day: number, phase: string): NoiseEvent[] {
  return NOISE_EVENTS.filter(e => day >= e.dayMin && day <= e.dayMax && e.phase === phase);
}

export const NOISE_EVENTS: NoiseEvent[] = [
  // ---- EUPHORIA (days 1-30) ----
  {
    id: 'eup-influencer-500',
    dayMin: 1,
    dayMax: 30,
    phase: 'euphoria',
    headline: 'VLRA to $500? Influencer With 2M Followers Says Yes',
    socialPost: 'Price targets are not analysis. A 2M-follower prediction with no valuation model is marketing, not signal.',
    source: 'ValuariaBets',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'A big number from a popular voice feeds the fear of missing out at the exact moment everyone else seems rich.',
    lessonIfFollowed: 'You chased a headline target into an extended position with no thesis, and paid for it when euphoria faded.',
  },
  {
    id: 'eup-quant-exits',
    dayMin: 1,
    dayMax: 30,
    phase: 'euphoria',
    headline: 'Renaissance Quant Quietly Exits — Should You?',
    socialPost: 'Someone smart sold, so the world must be ending... or they rebalanced. FUD on a solid holding deserves a look, not a panic.',
    source: 'QuantExit Weekly',
    bias: 'bear',
    correctAction: 'investigate',
    whyTempting: 'Smart-money departure stories trigger herd instinct; nobody wants to be the last one holding.',
    lessonIfFollowed: 'Investigating revealed the "exit" was routine profit-taking with the core position intact — panic selling would have been the mistake.',
  },
  {
    id: 'eup-tulip-mania',
    dayMin: 1,
    dayMax: 30,
    phase: 'euphoria',
    headline: 'Valuaria Mania: "This Time Is Different" Say Experts',
    socialPost: 'Every euphoria claims exemption from history. It never is. Check what the last 5 manias did.',
    source: 'The Hodl Street Journal',
    bias: 'euphoria',
    correctAction: 'ignore',
    whyTempting: 'The phrase "this time is different" is seductive because fundamentals genuinely improved — but the multiple improved more.',
    lessonIfFollowed: 'You extrapolated peak euphoria forever, held through the turn, and gave back everything.',
  },
  {
    id: 'eup-moonshot-list',
    dayMin: 1,
    dayMax: 30,
    phase: 'euphoria',
    headline: '7 Moonshots That Could 10x Before Christmas',
    socialPost: 'Listicles of lottery tickets are engagement bait. Lottery tickets are not a portfolio.',
    source: 'Moonshot Daily',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'Ten-bagger fantasy is irresistible when your neighbor just got one; the list does the daydreaming for you.',
    lessonIfFollowed: 'You scattered capital across seven lottery tickets and none of them paid for the eight losses they came with.',
  },

  // ---- SIDEWAYS (days 31-60) ----
  {
    id: 'side-hidden-100x',
    dayMin: 31,
    dayMax: 60,
    phase: 'sideways',
    headline: 'This Hidden 100x Coin Is Still Under $1',
    socialPost: 'Cheap is not a catalyst. A $0.90 asset needs a business case, not a decimal point.',
    source: 'ValuariaBets',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'A low absolute price feels like a bargain and a 100x is mathematically "only" $100 — until you check why it is under $1.',
    lessonIfFollowed: 'You bought the decimal point, not the business, and learned why the market priced it there.',
  },
  {
    id: 'side-broker-trim',
    dayMin: 31,
    dayMax: 60,
    phase: 'sideways',
    headline: 'Broker Report: Valuation Stretched, Trim Speculative Names',
    socialPost: 'Not every alarming headline is noise. A credible broker flagging stretched valuations is a real risk signal worth acting on.',
    source: 'The Hodl Street Journal',
    bias: 'bear',
    correctAction: 'investigate',
    whyTempting: 'The temptation is to dismiss it as more doom-slinging — that dismissal is exactly the trap.',
    lessonIfFollowed: 'Investigating confirmed the report and trimming speculative names later cushioned the drawdown; ignoring credible risk analysis cost real money.',
  },
  {
    id: 'side-sentiment-flat',
    dayMin: 31,
    dayMax: 60,
    phase: 'sideways',
    headline: 'Markets Going Nowhere: The "Dead Money" Problem',
    socialPost: 'Boredom is not a signal. Sideways markets are where patient compounding actually happens.',
    source: 'DipBuyer Daily',
    bias: 'bear',
    correctAction: 'ignore',
    whyTempting: 'Boredom makes cash itch; "dead money" pushes you to churn the portfolio for action.',
    lessonIfFollowed: 'You rotated repeatedly to escape boredom and paid fees, spreads, and taxes for the privilege of underperforming a flat market.',
  },
  {
    id: 'side-whale-alert',
    dayMin: 31,
    dayMax: 60,
    phase: 'sideways',
    headline: 'WHALE ALERT: 50M VLRA Moved to Exchange',
    socialPost: 'One wallet move is not a sell signal. Exchange inflows can be custody changes, hedges, or noise.',
    source: 'DiamondHands Gazette',
    bias: 'fear',
    correctAction: 'investigate',
    whyTempting: 'On-chain telemetry looks like insider information; the bearish implication feels like an edge.',
    lessonIfFollowed: 'Investigating showed it was a custody migration, not distribution — a real lesson in verifying before reacting.',
  },

  // ---- DECLINE (days 61-90) ----
  {
    id: 'decl-dip-gift',
    dayMin: 61,
    dayMax: 90,
    phase: 'decline',
    headline: 'The Dip Is a Gift: Buying Opportunity of the Decade',
    socialPost: 'During a genuine downtrend, every dip is "the bottom" — until it is not. Catching knives is not a strategy.',
    source: 'DipBuyer Daily',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'Averaging into falling prices feels disciplined and heroic while the trend is still pointing down.',
    lessonIfFollowed: 'You caught three knives on the way to the real bottom and ran out of capital exactly when the true buying window arrived.',
  },
  {
    id: 'decl-credit-spreads',
    dayMin: 61,
    dayMax: 90,
    phase: 'decline',
    headline: 'Credit Spreads Widening — Is Your Portfolio Hedged?',
    socialPost: 'This one is real. Widening credit spreads historically precede deeper equity stress. Hedging now is prudent, not fearful.',
    source: 'QuantExit Weekly',
    bias: 'bear',
    correctAction: 'hedge',
    whyTempting: 'The temptation is to call it bear-market fearmongering and stand pat — hedging feels like admitting defeat.',
    lessonIfFollowed: 'Hedged portfolios weathered the deepening decline; the un-hedged spent the crash at the mercy of forced selling.',
  },
  {
    id: 'decl-bull-case-intact',
    dayMin: 61,
    dayMax: 90,
    phase: 'decline',
    headline: 'Fundamentals Never Changed: The Bull Case Is Intact',
    socialPost: '"Fundamentals intact" is what every falling asset says on the way down. Price leads narrative by months.',
    source: 'ValuariaBets',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'Reassurance is what you want to hear mid-decline; the narrative comforts you into standing still.',
    lessonIfFollowed: 'You married the story instead of managing the position, and the "intact fundamentals" fell 60% with everything else.',
  },
  {
    id: 'decl-great-rotation',
    dayMin: 61,
    dayMax: 90,
    phase: 'decline',
    headline: 'The Great Rotation: Smart Money Rotating Into Value',
    socialPost: 'Rotation narratives justify any trade after the fact. Watch flows, not headlines about flows.',
    source: 'Moonshot Daily',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'It reframes the decline as a healthy transition, which is far more comfortable than "the trend is down."',
    lessonIfFollowed: 'You rotated into "value" in a falling market and discovered beta hits everything — the narrative sold comfort, not safety.',
  },

  // ---- CRASH (days 91-120) ----
  {
    id: 'crash-freefall',
    dayMin: 91,
    dayMax: 120,
    phase: 'crash',
    headline: 'MARKETS IN FREEFALL — Everything Must Go',
    socialPost: 'Panic selling into maximum fear is the textbook worst trade. Capitulation days often mark short-term bottoms.',
    source: 'The Hodl Street Journal',
    bias: 'fear',
    correctAction: 'investigate',
    whyTempting: 'The urge to make the pain stop is overwhelming; selling anything at any price feels like control.',
    lessonIfFollowed: 'Investigating found quality assets at generational discounts — panic sellers handed them to you. Selling here was the mistake of a lifetime.',
  },
  {
    id: 'crash-loss-porn',
    dayMin: 91,
    dayMax: 120,
    phase: 'crash',
    headline: 'I Lost Everything. Do Not Be Me.',
    socialPost: 'Loss porn spreads worst-case outcomes as if they were typical. It is emotional contagion, not data.',
    source: 'ValuariaBets',
    bias: 'fear',
    correctAction: 'ignore',
    whyTempting: 'Vivid personal losses hit harder than statistics; one catastrophe feels like proof that you are next.',
    lessonIfFollowed: 'You internalized someone else\'s overleveraged blowup as your own destiny and sold into the lowest prices of the cycle.',
  },
  {
    id: 'crash-401k-201k',
    dayMin: 91,
    dayMax: 120,
    phase: 'crash',
    headline: 'My 401k Is Now a 201k',
    socialPost: 'Mark-to-market pain is real but temporary for diversified holders. Panic at the bottom converts temporary loss into permanent loss.',
    source: 'DiamondHands Gazette',
    bias: 'fear',
    correctAction: 'ignore',
    whyTempting: 'The joke lands because the fear is real — humor is how the crowd processes panic, and it pulls you toward the exits too.',
    lessonIfFollowed: 'You let crowd gallows-humor set your risk decisions and locked in the drawdown permanently instead of waiting out the cycle.',
  },
  {
    id: 'crash-cash-is-king',
    dayMin: 91,
    dayMax: 120,
    phase: 'crash',
    headline: 'CASH IS KING: Why 100% Cash Is the Only Winning Move Now',
    socialPost: 'Going 100% cash at maximum pessimism guarantees you miss the recovery\'s violent first move.',
    source: 'Moonshot Daily',
    bias: 'fear',
    correctAction: 'investigate',
    whyTempting: 'Safety feels rational in freefall; the promise of zero further pain is almost irresistible.',
    lessonIfFollowed: 'Investigating showed historical recoveries begin amid maximum bad news — the all-cash move would have missed the entire rebound.',
  },

  // ---- RECOVERY (days 121-150) ----
  {
    id: 'rec-dead-cat',
    dayMin: 121,
    dayMax: 150,
    phase: 'recovery',
    headline: 'Dead Cat Bounce Or Real Recovery? Analysts Split',
    socialPost: 'Nobody calls the bottom in real time with certainty. Weigh evidence yourself instead of betting on either camp.',
    source: 'QuantExit Weekly',
    bias: 'bear',
    correctAction: 'investigate',
    whyTempting: 'The genuine uncertainty gives you an excuse to freeze — paralysis dressed up as prudence.',
    lessonIfFollowed: 'Investigating breadth, valuation, and liquidity pointed to a genuine recovery; waiting for unanimous agreement meant buying well off the lows.',
  },
  {
    id: 'rec-missed-bottom',
    dayMin: 121,
    dayMax: 150,
    phase: 'recovery',
    headline: "Missed the Bottom? Here's Why You Haven't",
    socialPost: 'Recovery euphoria re-forms fast. "Still early" is the same FOMO engine from the last peak, wearing new clothes.',
    source: 'Moonshot Daily',
    bias: 'euphoria',
    correctAction: 'ignore',
    whyTempting: 'The fear of missing the next leg is powerful — you just watched an opportunity pass, so the next one feels mandatory.',
    lessonIfFollowed: 'You chased speculative froth early in a young recovery, held through the next correction, and repeated the cycle exactly as designed.',
  },
  {
    id: 'rec-v-shape',
    dayMin: 121,
    dayMax: 150,
    phase: 'recovery',
    headline: 'The V-Shaped Recovery Is Here: All-Time Highs by Fall',
    socialPost: 'Linear extrapolation of a strong bounce ignores the damage done. Recoveries zig, zag, and retest.',
    source: 'The Hodl Street Journal',
    bias: 'bull',
    correctAction: 'ignore',
    whyTempting: 'After months of pain, the promise that the worst is over and a straight line up is coming feels like permission to relax.',
    lessonIfFollowed: 'You maxed leverage on a straight-line forecast, and the retest nobody predicted took out your stops before the real rally resumed.',
  },
  {
    id: 'rec-survivors-list',
    dayMin: 121,
    dayMax: 150,
    phase: 'recovery',
    headline: '5 Survivors That Will Lead the Next Bull Market',
    socialPost: 'Survivorship lists are written by the winners; the casualties are silently edited out. Verify balance sheets yourself.',
    source: 'DipBuyer Daily',
    bias: 'bull',
    correctAction: 'investigate',
    whyTempting: 'Post-crash, picking the "leaders" feels like the whole game — and the list does the homework you skipped.',
    lessonIfFollowed: 'Investigating found two of the five carried unsustainable debt into the recovery; the list was a headline, not diligence.',
  },
];
